### PR TITLE
Issue #12: add Herb as maintainer

### LINKED ISSUE #12: Update maintainers in README.md?
@jenlampton this project is abandoned. ~We should change the README to "seeking maintainers".~ All recent commits are by people other than the maintainer (who has had no activity on this project for a few years).

~PR https://github.com/backdrop-contrib/flag/pull/13~

Update: I'm willing to maintain this module so a new PR coming.

### PR DESCRIPTION
**Pull request by herbdool**
Fixes #12

### CODE REVIEW

**Comment by herbdool** [comment]
@klonos I guess I might need you to change permissions on this project if I'm to become the maintainer. Thanks!

**Comment by klonos** [comment]
Hey @herbdool 👋🏼 please ping me on Zulip once approval by the current maintainer has been provided (from what I see in #12 it may already be implied)

**Comment by herbdool** [comment]
I think it's pretty explicit: he's okay with anyone who steps forward. And he's mentioned it here https://github.com/backdrop-contrib/flag/issues/17. Do we need to still wait @klonos?

**Comment by laryn** [comment]
@klonos @herbdool It seems not just implied but explicitly okayed:

 - https://github.com/backdrop-contrib/flag/issues/12#issuecomment-472975840

**Comment by herbdool** [comment]
@klonos @jenlampton can you give me maintainer access to this project?

**Comment by jenlampton** [comment]
Done!

**Pull request merged**
